//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.ShawServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeaturedItems", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class FeaturedItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.ShawServices.FeaturedItem[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.ShawServices.ShawHyperLink[] LinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.ShawServices.ShawHyperLink TitleLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ViewTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.ShawServices.FeaturedItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.ShawServices.ShawHyperLink[] Links {
            get {
                return this.LinksField;
            }
            set {
                if ((object.ReferenceEquals(this.LinksField, value) != true)) {
                    this.LinksField = value;
                    this.RaisePropertyChanged("Links");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.ShawServices.ShawHyperLink TitleLink {
            get {
                return this.TitleLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleLinkField, value) != true)) {
                    this.TitleLinkField = value;
                    this.RaisePropertyChanged("TitleLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ViewTypes {
            get {
                return this.ViewTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.ViewTypesField, value) != true)) {
                    this.ViewTypesField = value;
                    this.RaisePropertyChanged("ViewTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShawHyperLink", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class ShawHyperLink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Href {
            get {
                return this.HrefField;
            }
            set {
                if ((object.ReferenceEquals(this.HrefField, value) != true)) {
                    this.HrefField = value;
                    this.RaisePropertyChanged("Href");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeaturedItem", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class FeaturedItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.ShawServices.ShawHyperLink[] CallToActionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbnailURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.ShawServices.ShawHyperLink TitleLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViewTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.ShawServices.ShawHyperLink[] CallToActions {
            get {
                return this.CallToActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CallToActionsField, value) != true)) {
                    this.CallToActionsField = value;
                    this.RaisePropertyChanged("CallToActions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateField, value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbnailURL {
            get {
                return this.ThumbnailURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbnailURLField, value) != true)) {
                    this.ThumbnailURLField = value;
                    this.RaisePropertyChanged("ThumbnailURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.ShawServices.ShawHyperLink TitleLink {
            get {
                return this.TitleLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleLinkField, value) != true)) {
                    this.TitleLinkField = value;
                    this.RaisePropertyChanged("TitleLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViewType {
            get {
                return this.ViewTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ViewTypeField, value) != true)) {
                    this.ViewTypeField = value;
                    this.RaisePropertyChanged("ViewType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShawServices.IFeaturedItems")]
    public interface IFeaturedItems {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeaturedItems/GetAllItems", ReplyAction="http://tempuri.org/IFeaturedItems/GetAllItemsResponse")]
        MvcApplication1.ShawServices.FeaturedItems[] GetAllItems(string host, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeaturedItems/GetAllItems", ReplyAction="http://tempuri.org/IFeaturedItems/GetAllItemsResponse")]
        System.Threading.Tasks.Task<MvcApplication1.ShawServices.FeaturedItems[]> GetAllItemsAsync(string host, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeaturedItems/GetItem", ReplyAction="http://tempuri.org/IFeaturedItems/GetItemResponse")]
        MvcApplication1.ShawServices.FeaturedItems GetItem(string host, string version, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeaturedItems/GetItem", ReplyAction="http://tempuri.org/IFeaturedItems/GetItemResponse")]
        System.Threading.Tasks.Task<MvcApplication1.ShawServices.FeaturedItems> GetItemAsync(string host, string version, string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeaturedItemsChannel : MvcApplication1.ShawServices.IFeaturedItems, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeaturedItemsClient : System.ServiceModel.ClientBase<MvcApplication1.ShawServices.IFeaturedItems>, MvcApplication1.ShawServices.IFeaturedItems {
        
        public FeaturedItemsClient() {
        }
        
        public FeaturedItemsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeaturedItemsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeaturedItemsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeaturedItemsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MvcApplication1.ShawServices.FeaturedItems[] GetAllItems(string host, string version) {
            return base.Channel.GetAllItems(host, version);
        }
        
        public System.Threading.Tasks.Task<MvcApplication1.ShawServices.FeaturedItems[]> GetAllItemsAsync(string host, string version) {
            return base.Channel.GetAllItemsAsync(host, version);
        }
        
        public MvcApplication1.ShawServices.FeaturedItems GetItem(string host, string version, string id) {
            return base.Channel.GetItem(host, version, id);
        }
        
        public System.Threading.Tasks.Task<MvcApplication1.ShawServices.FeaturedItems> GetItemAsync(string host, string version, string id) {
            return base.Channel.GetItemAsync(host, version, id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShawServices.IGalleries")]
    public interface IGalleries {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGalleries/GetAll", ReplyAction="http://tempuri.org/IGalleries/GetAllResponse")]
        string GetAll(string host, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGalleries/GetAll", ReplyAction="http://tempuri.org/IGalleries/GetAllResponse")]
        System.Threading.Tasks.Task<string> GetAllAsync(string host, string version);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGalleriesChannel : MvcApplication1.ShawServices.IGalleries, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GalleriesClient : System.ServiceModel.ClientBase<MvcApplication1.ShawServices.IGalleries>, MvcApplication1.ShawServices.IGalleries {
        
        public GalleriesClient() {
        }
        
        public GalleriesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GalleriesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GalleriesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GalleriesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAll(string host, string version) {
            return base.Channel.GetAll(host, version);
        }
        
        public System.Threading.Tasks.Task<string> GetAllAsync(string host, string version) {
            return base.Channel.GetAllAsync(host, version);
        }
    }
}
