//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFeaturedItems")]
    public interface IFeaturedItems {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeaturedItems/GetAllItems", ReplyAction="http://tempuri.org/IFeaturedItems/GetAllItemsResponse")]
        string GetAllItems(string host, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeaturedItems/GetAllItems", ReplyAction="http://tempuri.org/IFeaturedItems/GetAllItemsResponse")]
        System.Threading.Tasks.Task<string> GetAllItemsAsync(string host, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeaturedItems/GetItem", ReplyAction="http://tempuri.org/IFeaturedItems/GetItemResponse")]
        string GetItem(string host, string version, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeaturedItems/GetItem", ReplyAction="http://tempuri.org/IFeaturedItems/GetItemResponse")]
        System.Threading.Tasks.Task<string> GetItemAsync(string host, string version, string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeaturedItemsChannel : MvcApplication1.ServiceReference1.IFeaturedItems, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeaturedItemsClient : System.ServiceModel.ClientBase<MvcApplication1.ServiceReference1.IFeaturedItems>, MvcApplication1.ServiceReference1.IFeaturedItems {
        
        public FeaturedItemsClient() {
        }
        
        public FeaturedItemsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeaturedItemsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeaturedItemsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeaturedItemsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllItems(string host, string version) {
            return base.Channel.GetAllItems(host, version);
        }
        
        public System.Threading.Tasks.Task<string> GetAllItemsAsync(string host, string version) {
            return base.Channel.GetAllItemsAsync(host, version);
        }
        
        public string GetItem(string host, string version, string id) {
            return base.Channel.GetItem(host, version, id);
        }
        
        public System.Threading.Tasks.Task<string> GetItemAsync(string host, string version, string id) {
            return base.Channel.GetItemAsync(host, version, id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGalleries")]
    public interface IGalleries {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGalleries/GetAll", ReplyAction="http://tempuri.org/IGalleries/GetAllResponse")]
        string GetAll(string host, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGalleries/GetAll", ReplyAction="http://tempuri.org/IGalleries/GetAllResponse")]
        System.Threading.Tasks.Task<string> GetAllAsync(string host, string version);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGalleriesChannel : MvcApplication1.ServiceReference1.IGalleries, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GalleriesClient : System.ServiceModel.ClientBase<MvcApplication1.ServiceReference1.IGalleries>, MvcApplication1.ServiceReference1.IGalleries {
        
        public GalleriesClient() {
        }
        
        public GalleriesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GalleriesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GalleriesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GalleriesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAll(string host, string version) {
            return base.Channel.GetAll(host, version);
        }
        
        public System.Threading.Tasks.Task<string> GetAllAsync(string host, string version) {
            return base.Channel.GetAllAsync(host, version);
        }
    }
}
